name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: expected-behavior
    attributes:
      label: Describe expected behavior?
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Describe Actual Behavior?
    validations:
      required: true
  - type: textarea
    id: provide-example
    attributes:
      label: Provide a example!
    validations:
      required: true
  - type: textarea
    id: provide-informations
    attributes:
      label: Provide more informations if to think necessary
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of your operation system?
      options:
        - Windows
        - MacOS
        - Linux
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
